//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace GeoSearch.OtherQueryFunctionsServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WMSLayers", Namespace="http://schemas.datacontract.org/2004/07/GeoSearch.Web")]
    public partial class WMSLayers : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string WMSURLField;
        
        private GeoSearch.OtherQueryFunctionsServiceReference.BBox boxField;
        
        private System.Collections.ObjectModel.ObservableCollection<GeoSearch.OtherQueryFunctionsServiceReference.WMSLayer> layersListField;
        
        private string nameField;
        
        private string titleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WMSURL {
            get {
                return this.WMSURLField;
            }
            set {
                if ((object.ReferenceEquals(this.WMSURLField, value) != true)) {
                    this.WMSURLField = value;
                    this.RaisePropertyChanged("WMSURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GeoSearch.OtherQueryFunctionsServiceReference.BBox box {
            get {
                return this.boxField;
            }
            set {
                if ((object.ReferenceEquals(this.boxField, value) != true)) {
                    this.boxField = value;
                    this.RaisePropertyChanged("box");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GeoSearch.OtherQueryFunctionsServiceReference.WMSLayer> layersList {
            get {
                return this.layersListField;
            }
            set {
                if ((object.ReferenceEquals(this.layersListField, value) != true)) {
                    this.layersListField = value;
                    this.RaisePropertyChanged("layersList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BBox", Namespace="http://schemas.datacontract.org/2004/07/GeoSearch.Web")]
    public partial class BBox : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string BBox_CRSField;
        
        private double BBox_Lower_LatField;
        
        private double BBox_Lower_LonField;
        
        private double BBox_Upper_LatField;
        
        private double BBox_Upper_LonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BBox_CRS {
            get {
                return this.BBox_CRSField;
            }
            set {
                if ((object.ReferenceEquals(this.BBox_CRSField, value) != true)) {
                    this.BBox_CRSField = value;
                    this.RaisePropertyChanged("BBox_CRS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BBox_Lower_Lat {
            get {
                return this.BBox_Lower_LatField;
            }
            set {
                if ((this.BBox_Lower_LatField.Equals(value) != true)) {
                    this.BBox_Lower_LatField = value;
                    this.RaisePropertyChanged("BBox_Lower_Lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BBox_Lower_Lon {
            get {
                return this.BBox_Lower_LonField;
            }
            set {
                if ((this.BBox_Lower_LonField.Equals(value) != true)) {
                    this.BBox_Lower_LonField = value;
                    this.RaisePropertyChanged("BBox_Lower_Lon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BBox_Upper_Lat {
            get {
                return this.BBox_Upper_LatField;
            }
            set {
                if ((this.BBox_Upper_LatField.Equals(value) != true)) {
                    this.BBox_Upper_LatField = value;
                    this.RaisePropertyChanged("BBox_Upper_Lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BBox_Upper_Lon {
            get {
                return this.BBox_Upper_LonField;
            }
            set {
                if ((this.BBox_Upper_LonField.Equals(value) != true)) {
                    this.BBox_Upper_LonField = value;
                    this.RaisePropertyChanged("BBox_Upper_Lon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WMSLayer", Namespace="http://schemas.datacontract.org/2004/07/GeoSearch.Web")]
    public partial class WMSLayer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GeoSearch.OtherQueryFunctionsServiceReference.BBox boxField;
        
        private string nameField;
        
        private double rankValueField;
        
        private double responseTimeField;
        
        private string titleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GeoSearch.OtherQueryFunctionsServiceReference.BBox box {
            get {
                return this.boxField;
            }
            set {
                if ((object.ReferenceEquals(this.boxField, value) != true)) {
                    this.boxField = value;
                    this.RaisePropertyChanged("box");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double rankValue {
            get {
                return this.rankValueField;
            }
            set {
                if ((this.rankValueField.Equals(value) != true)) {
                    this.rankValueField = value;
                    this.RaisePropertyChanged("rankValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double responseTime {
            get {
                return this.responseTimeField;
            }
            set {
                if ((this.responseTimeField.Equals(value) != true)) {
                    this.responseTimeField = value;
                    this.RaisePropertyChanged("responseTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HierachicalWMSLayers", Namespace="http://schemas.datacontract.org/2004/07/GeoSearch.Web")]
    public partial class HierachicalWMSLayers : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string WMSURLField;
        
        private int allGetMapEnabledLayers_NumberField;
        
        private GeoSearch.OtherQueryFunctionsServiceReference.BBox latLonBBoxField;
        
        private System.Collections.ObjectModel.ObservableCollection<GeoSearch.OtherQueryFunctionsServiceReference.CascadedWMSLayer> layersListField;
        
        private System.Collections.ObjectModel.ObservableCollection<GeoSearch.OtherQueryFunctionsServiceReference.BBox> otherCRSBBoxListField;
        
        private string serviceNameField;
        
        private string serviceTitleField;
        
        private int subLayers_NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WMSURL {
            get {
                return this.WMSURLField;
            }
            set {
                if ((object.ReferenceEquals(this.WMSURLField, value) != true)) {
                    this.WMSURLField = value;
                    this.RaisePropertyChanged("WMSURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int allGetMapEnabledLayers_Number {
            get {
                return this.allGetMapEnabledLayers_NumberField;
            }
            set {
                if ((this.allGetMapEnabledLayers_NumberField.Equals(value) != true)) {
                    this.allGetMapEnabledLayers_NumberField = value;
                    this.RaisePropertyChanged("allGetMapEnabledLayers_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GeoSearch.OtherQueryFunctionsServiceReference.BBox latLonBBox {
            get {
                return this.latLonBBoxField;
            }
            set {
                if ((object.ReferenceEquals(this.latLonBBoxField, value) != true)) {
                    this.latLonBBoxField = value;
                    this.RaisePropertyChanged("latLonBBox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GeoSearch.OtherQueryFunctionsServiceReference.CascadedWMSLayer> layersList {
            get {
                return this.layersListField;
            }
            set {
                if ((object.ReferenceEquals(this.layersListField, value) != true)) {
                    this.layersListField = value;
                    this.RaisePropertyChanged("layersList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GeoSearch.OtherQueryFunctionsServiceReference.BBox> otherCRSBBoxList {
            get {
                return this.otherCRSBBoxListField;
            }
            set {
                if ((object.ReferenceEquals(this.otherCRSBBoxListField, value) != true)) {
                    this.otherCRSBBoxListField = value;
                    this.RaisePropertyChanged("otherCRSBBoxList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serviceName {
            get {
                return this.serviceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.serviceNameField, value) != true)) {
                    this.serviceNameField = value;
                    this.RaisePropertyChanged("serviceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serviceTitle {
            get {
                return this.serviceTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.serviceTitleField, value) != true)) {
                    this.serviceTitleField = value;
                    this.RaisePropertyChanged("serviceTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int subLayers_Number {
            get {
                return this.subLayers_NumberField;
            }
            set {
                if ((this.subLayers_NumberField.Equals(value) != true)) {
                    this.subLayers_NumberField = value;
                    this.RaisePropertyChanged("subLayers_Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CascadedWMSLayer", Namespace="http://schemas.datacontract.org/2004/07/GeoSearch.Web")]
    public partial class CascadedWMSLayer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<GeoSearch.OtherQueryFunctionsServiceReference.CascadedWMSLayer> ChildrenField;
        
        private bool canGetMapField;
        
        private string extent_timeField;
        
        private string extent_time_defaultField;
        
        private GeoSearch.OtherQueryFunctionsServiceReference.BBox latLonBBoxField;
        
        private string legendURLField;
        
        private string nameField;
        
        private System.Collections.ObjectModel.ObservableCollection<GeoSearch.OtherQueryFunctionsServiceReference.BBox> otherCRSBBoxListField;
        
        private bool queryableField;
        
        private double rankValueField;
        
        private double responseTimeField;
        
        private bool timeEnabledField;
        
        private string titleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GeoSearch.OtherQueryFunctionsServiceReference.CascadedWMSLayer> Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool canGetMap {
            get {
                return this.canGetMapField;
            }
            set {
                if ((this.canGetMapField.Equals(value) != true)) {
                    this.canGetMapField = value;
                    this.RaisePropertyChanged("canGetMap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string extent_time {
            get {
                return this.extent_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.extent_timeField, value) != true)) {
                    this.extent_timeField = value;
                    this.RaisePropertyChanged("extent_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string extent_time_default {
            get {
                return this.extent_time_defaultField;
            }
            set {
                if ((object.ReferenceEquals(this.extent_time_defaultField, value) != true)) {
                    this.extent_time_defaultField = value;
                    this.RaisePropertyChanged("extent_time_default");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GeoSearch.OtherQueryFunctionsServiceReference.BBox latLonBBox {
            get {
                return this.latLonBBoxField;
            }
            set {
                if ((object.ReferenceEquals(this.latLonBBoxField, value) != true)) {
                    this.latLonBBoxField = value;
                    this.RaisePropertyChanged("latLonBBox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string legendURL {
            get {
                return this.legendURLField;
            }
            set {
                if ((object.ReferenceEquals(this.legendURLField, value) != true)) {
                    this.legendURLField = value;
                    this.RaisePropertyChanged("legendURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GeoSearch.OtherQueryFunctionsServiceReference.BBox> otherCRSBBoxList {
            get {
                return this.otherCRSBBoxListField;
            }
            set {
                if ((object.ReferenceEquals(this.otherCRSBBoxListField, value) != true)) {
                    this.otherCRSBBoxListField = value;
                    this.RaisePropertyChanged("otherCRSBBoxList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool queryable {
            get {
                return this.queryableField;
            }
            set {
                if ((this.queryableField.Equals(value) != true)) {
                    this.queryableField = value;
                    this.RaisePropertyChanged("queryable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double rankValue {
            get {
                return this.rankValueField;
            }
            set {
                if ((this.rankValueField.Equals(value) != true)) {
                    this.rankValueField = value;
                    this.RaisePropertyChanged("rankValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double responseTime {
            get {
                return this.responseTimeField;
            }
            set {
                if ((this.responseTimeField.Equals(value) != true)) {
                    this.responseTimeField = value;
                    this.RaisePropertyChanged("responseTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool timeEnabled {
            get {
                return this.timeEnabledField;
            }
            set {
                if ((this.timeEnabledField.Equals(value) != true)) {
                    this.timeEnabledField = value;
                    this.RaisePropertyChanged("timeEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="cisc.gmu.edu/OtherQueryFunctionsService", ConfigurationName="OtherQueryFunctionsServiceReference.OtherQueryFunctionsService")]
    public interface OtherQueryFunctionsService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="cisc.gmu.edu/OtherQueryFunctionsService/OtherQueryFunctionsService/getRecordDetai" +
            "lMetadata", ReplyAction="cisc.gmu.edu/OtherQueryFunctionsService/OtherQueryFunctionsService/getRecordDetai" +
            "lMetadataResponse")]
        System.IAsyncResult BegingetRecordDetailMetadata(string MetadataAccessURL, System.AsyncCallback callback, object asyncState);
        
        string EndgetRecordDetailMetadata(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="cisc.gmu.edu/OtherQueryFunctionsService/OtherQueryFunctionsService/getAllLayerNam" +
            "esOfWMS", ReplyAction="cisc.gmu.edu/OtherQueryFunctionsService/OtherQueryFunctionsService/getAllLayerNam" +
            "esOfWMSResponse")]
        System.IAsyncResult BegingetAllLayerNamesOfWMS(string urlstring, System.AsyncCallback callback, object asyncState);
        
        GeoSearch.OtherQueryFunctionsServiceReference.WMSLayers EndgetAllLayerNamesOfWMS(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="cisc.gmu.edu/OtherQueryFunctionsService/OtherQueryFunctionsService/getHierachical" +
            "LayersOfWMS", ReplyAction="cisc.gmu.edu/OtherQueryFunctionsService/OtherQueryFunctionsService/getHierachical" +
            "LayersOfWMSResponse")]
        System.IAsyncResult BegingetHierachicalLayersOfWMS(string urlstring, System.AsyncCallback callback, object asyncState);
        
        GeoSearch.OtherQueryFunctionsServiceReference.HierachicalWMSLayers EndgetHierachicalLayersOfWMS(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OtherQueryFunctionsServiceChannel : GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getRecordDetailMetadataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getRecordDetailMetadataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAllLayerNamesOfWMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getAllLayerNamesOfWMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GeoSearch.OtherQueryFunctionsServiceReference.WMSLayers Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GeoSearch.OtherQueryFunctionsServiceReference.WMSLayers)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getHierachicalLayersOfWMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getHierachicalLayersOfWMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GeoSearch.OtherQueryFunctionsServiceReference.HierachicalWMSLayers Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GeoSearch.OtherQueryFunctionsServiceReference.HierachicalWMSLayers)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OtherQueryFunctionsServiceClient : System.ServiceModel.ClientBase<GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService>, GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService {
        
        private BeginOperationDelegate onBegingetRecordDetailMetadataDelegate;
        
        private EndOperationDelegate onEndgetRecordDetailMetadataDelegate;
        
        private System.Threading.SendOrPostCallback ongetRecordDetailMetadataCompletedDelegate;
        
        private BeginOperationDelegate onBegingetAllLayerNamesOfWMSDelegate;
        
        private EndOperationDelegate onEndgetAllLayerNamesOfWMSDelegate;
        
        private System.Threading.SendOrPostCallback ongetAllLayerNamesOfWMSCompletedDelegate;
        
        private BeginOperationDelegate onBegingetHierachicalLayersOfWMSDelegate;
        
        private EndOperationDelegate onEndgetHierachicalLayersOfWMSDelegate;
        
        private System.Threading.SendOrPostCallback ongetHierachicalLayersOfWMSCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public OtherQueryFunctionsServiceClient() {
        }
        
        public OtherQueryFunctionsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OtherQueryFunctionsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OtherQueryFunctionsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OtherQueryFunctionsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getRecordDetailMetadataCompletedEventArgs> getRecordDetailMetadataCompleted;
        
        public event System.EventHandler<getAllLayerNamesOfWMSCompletedEventArgs> getAllLayerNamesOfWMSCompleted;
        
        public event System.EventHandler<getHierachicalLayersOfWMSCompletedEventArgs> getHierachicalLayersOfWMSCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService.BegingetRecordDetailMetadata(string MetadataAccessURL, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetRecordDetailMetadata(MetadataAccessURL, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService.EndgetRecordDetailMetadata(System.IAsyncResult result) {
            return base.Channel.EndgetRecordDetailMetadata(result);
        }
        
        private System.IAsyncResult OnBegingetRecordDetailMetadata(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string MetadataAccessURL = ((string)(inValues[0]));
            return ((GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService)(this)).BegingetRecordDetailMetadata(MetadataAccessURL, callback, asyncState);
        }
        
        private object[] OnEndgetRecordDetailMetadata(System.IAsyncResult result) {
            string retVal = ((GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService)(this)).EndgetRecordDetailMetadata(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetRecordDetailMetadataCompleted(object state) {
            if ((this.getRecordDetailMetadataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getRecordDetailMetadataCompleted(this, new getRecordDetailMetadataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getRecordDetailMetadataAsync(string MetadataAccessURL) {
            this.getRecordDetailMetadataAsync(MetadataAccessURL, null);
        }
        
        public void getRecordDetailMetadataAsync(string MetadataAccessURL, object userState) {
            if ((this.onBegingetRecordDetailMetadataDelegate == null)) {
                this.onBegingetRecordDetailMetadataDelegate = new BeginOperationDelegate(this.OnBegingetRecordDetailMetadata);
            }
            if ((this.onEndgetRecordDetailMetadataDelegate == null)) {
                this.onEndgetRecordDetailMetadataDelegate = new EndOperationDelegate(this.OnEndgetRecordDetailMetadata);
            }
            if ((this.ongetRecordDetailMetadataCompletedDelegate == null)) {
                this.ongetRecordDetailMetadataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetRecordDetailMetadataCompleted);
            }
            base.InvokeAsync(this.onBegingetRecordDetailMetadataDelegate, new object[] {
                        MetadataAccessURL}, this.onEndgetRecordDetailMetadataDelegate, this.ongetRecordDetailMetadataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService.BegingetAllLayerNamesOfWMS(string urlstring, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetAllLayerNamesOfWMS(urlstring, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeoSearch.OtherQueryFunctionsServiceReference.WMSLayers GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService.EndgetAllLayerNamesOfWMS(System.IAsyncResult result) {
            return base.Channel.EndgetAllLayerNamesOfWMS(result);
        }
        
        private System.IAsyncResult OnBegingetAllLayerNamesOfWMS(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string urlstring = ((string)(inValues[0]));
            return ((GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService)(this)).BegingetAllLayerNamesOfWMS(urlstring, callback, asyncState);
        }
        
        private object[] OnEndgetAllLayerNamesOfWMS(System.IAsyncResult result) {
            GeoSearch.OtherQueryFunctionsServiceReference.WMSLayers retVal = ((GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService)(this)).EndgetAllLayerNamesOfWMS(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAllLayerNamesOfWMSCompleted(object state) {
            if ((this.getAllLayerNamesOfWMSCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAllLayerNamesOfWMSCompleted(this, new getAllLayerNamesOfWMSCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAllLayerNamesOfWMSAsync(string urlstring) {
            this.getAllLayerNamesOfWMSAsync(urlstring, null);
        }
        
        public void getAllLayerNamesOfWMSAsync(string urlstring, object userState) {
            if ((this.onBegingetAllLayerNamesOfWMSDelegate == null)) {
                this.onBegingetAllLayerNamesOfWMSDelegate = new BeginOperationDelegate(this.OnBegingetAllLayerNamesOfWMS);
            }
            if ((this.onEndgetAllLayerNamesOfWMSDelegate == null)) {
                this.onEndgetAllLayerNamesOfWMSDelegate = new EndOperationDelegate(this.OnEndgetAllLayerNamesOfWMS);
            }
            if ((this.ongetAllLayerNamesOfWMSCompletedDelegate == null)) {
                this.ongetAllLayerNamesOfWMSCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAllLayerNamesOfWMSCompleted);
            }
            base.InvokeAsync(this.onBegingetAllLayerNamesOfWMSDelegate, new object[] {
                        urlstring}, this.onEndgetAllLayerNamesOfWMSDelegate, this.ongetAllLayerNamesOfWMSCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService.BegingetHierachicalLayersOfWMS(string urlstring, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetHierachicalLayersOfWMS(urlstring, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeoSearch.OtherQueryFunctionsServiceReference.HierachicalWMSLayers GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService.EndgetHierachicalLayersOfWMS(System.IAsyncResult result) {
            return base.Channel.EndgetHierachicalLayersOfWMS(result);
        }
        
        private System.IAsyncResult OnBegingetHierachicalLayersOfWMS(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string urlstring = ((string)(inValues[0]));
            return ((GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService)(this)).BegingetHierachicalLayersOfWMS(urlstring, callback, asyncState);
        }
        
        private object[] OnEndgetHierachicalLayersOfWMS(System.IAsyncResult result) {
            GeoSearch.OtherQueryFunctionsServiceReference.HierachicalWMSLayers retVal = ((GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService)(this)).EndgetHierachicalLayersOfWMS(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetHierachicalLayersOfWMSCompleted(object state) {
            if ((this.getHierachicalLayersOfWMSCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getHierachicalLayersOfWMSCompleted(this, new getHierachicalLayersOfWMSCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getHierachicalLayersOfWMSAsync(string urlstring) {
            this.getHierachicalLayersOfWMSAsync(urlstring, null);
        }
        
        public void getHierachicalLayersOfWMSAsync(string urlstring, object userState) {
            if ((this.onBegingetHierachicalLayersOfWMSDelegate == null)) {
                this.onBegingetHierachicalLayersOfWMSDelegate = new BeginOperationDelegate(this.OnBegingetHierachicalLayersOfWMS);
            }
            if ((this.onEndgetHierachicalLayersOfWMSDelegate == null)) {
                this.onEndgetHierachicalLayersOfWMSDelegate = new EndOperationDelegate(this.OnEndgetHierachicalLayersOfWMS);
            }
            if ((this.ongetHierachicalLayersOfWMSCompletedDelegate == null)) {
                this.ongetHierachicalLayersOfWMSCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetHierachicalLayersOfWMSCompleted);
            }
            base.InvokeAsync(this.onBegingetHierachicalLayersOfWMSDelegate, new object[] {
                        urlstring}, this.onEndgetHierachicalLayersOfWMSDelegate, this.ongetHierachicalLayersOfWMSCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService CreateChannel() {
            return new OtherQueryFunctionsServiceClientChannel(this);
        }
        
        private class OtherQueryFunctionsServiceClientChannel : ChannelBase<GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService>, GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService {
            
            public OtherQueryFunctionsServiceClientChannel(System.ServiceModel.ClientBase<GeoSearch.OtherQueryFunctionsServiceReference.OtherQueryFunctionsService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetRecordDetailMetadata(string MetadataAccessURL, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = MetadataAccessURL;
                System.IAsyncResult _result = base.BeginInvoke("getRecordDetailMetadata", _args, callback, asyncState);
                return _result;
            }
            
            public string EndgetRecordDetailMetadata(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("getRecordDetailMetadata", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetAllLayerNamesOfWMS(string urlstring, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = urlstring;
                System.IAsyncResult _result = base.BeginInvoke("getAllLayerNamesOfWMS", _args, callback, asyncState);
                return _result;
            }
            
            public GeoSearch.OtherQueryFunctionsServiceReference.WMSLayers EndgetAllLayerNamesOfWMS(System.IAsyncResult result) {
                object[] _args = new object[0];
                GeoSearch.OtherQueryFunctionsServiceReference.WMSLayers _result = ((GeoSearch.OtherQueryFunctionsServiceReference.WMSLayers)(base.EndInvoke("getAllLayerNamesOfWMS", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetHierachicalLayersOfWMS(string urlstring, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = urlstring;
                System.IAsyncResult _result = base.BeginInvoke("getHierachicalLayersOfWMS", _args, callback, asyncState);
                return _result;
            }
            
            public GeoSearch.OtherQueryFunctionsServiceReference.HierachicalWMSLayers EndgetHierachicalLayersOfWMS(System.IAsyncResult result) {
                object[] _args = new object[0];
                GeoSearch.OtherQueryFunctionsServiceReference.HierachicalWMSLayers _result = ((GeoSearch.OtherQueryFunctionsServiceReference.HierachicalWMSLayers)(base.EndInvoke("getHierachicalLayersOfWMS", _args, result)));
                return _result;
            }
        }
    }
}
